# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(null=True, related_name='favorite', to='quotes.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_submit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_submit', to='quotes.User'),
        ),
    ]
