# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20171025_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to='quotes.User'),
        ),
    ]
